language: python
python: 3.7
env:
  matrix:
    - TOX_ENV=flake8
    - TOX_ENV=safety
    - TOX_ENV=py37
    - TOX_ENV=coveralls
install:
  - pipenv install tox
script:
  - tox -e $TOX_ENV
jobs:
  include:
    - stage: Deploy
      install: pip install awscli
      script: skip
      before_deploy: make dist
      deploy: 
        skip_cleanup: true
        provider: script
        script: make publish
