version: "3.7"
services:
  web:
    image: airflow
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres@db/postgres"
    command: ["webserver"]
  scheduler:
    image: airflow
    build: .
    depends_on:
      - db
    environment:
      AIRFLOW__CORE__DAGS_FOLDER: "/airflow/dags"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres@db/postgres"
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 30
    command: ["scheduler"]
    volumes:
      - type: bind
        source: ./workflows
        target: /airflow/dags
  db:
   image: postgres
   volumes:
     - type: volume
       source: db
       target: /var/lib/postgresql/data
volumes:
  db:
