version: "3.7"
services:
  initialize:
    image: airflow
    build: .
    depends_on:
      - db
    environment:
      AIRFLOW__CORE__DAGS_FOLDER: "/airflow/dags"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres@db/postgres"
      AIRFLOW__CORE__EXECUTOR: "CeleryExecutor"
      AIRFLOW__CELERY__BROKER_URL: "redis://redis:6379"
      AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://postgres@db/postgres"
    command: ["initdb"]
    networks:
      - airflow_init
  db:
   image: postgres
   volumes:
     - type: volume
       source: db
       target: /var/lib/postgresql/data
   networks:
     - airflow_init
volumes:
  db:
networks:
  airflow_init:
