version: "3.7"
services:
  initialize:
    image: airflow
    build: .
    depends_on:
      - db
    environment:
      AIRFLOW__CORE__DAGS_FOLDER: "/airflow/dags"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres@db/postgres"
    command: ["initdb"]
  db:
   image: postgres
   volumes:
     - type: volume
       source: db
       target: /var/lib/postgresql/data
volumes:
  db:
